### ISSUE TITLE
Unknown bug ?

### ISSUE THREAD

**Issue by hai-nguyen-van** [thpani/hdapsicon#1]
Hello,

I am trying to make this applet work on my ThinkPad X1 with Ubuntu 12.04. The [HDAPS daemon](https://github.com/evgeni/hdapsd) already works and listens to `/dev/input/event6` as shown below : 

```
 * Restarting IBM Hard Disk Active Protection System (HDAPS) daemon hdapsd
Mon Feb 16 01:14:31 2015: Starting hdapsd
Mon Feb 16 01:14:31 2015: Selected interface: HDAPS
Mon Feb 16 01:14:31 2015: Selected HDAPS input device: /dev/input/event6
```

However, `hdapsicon` is **unable** to work and only shows the error icon while showing **no** error message...

**Comment by thpani** [comment]
What message does the tooltip show when you hover the mouse cursor over the icon?

Can you check if the file `/sys/block/{{devicename}}/device/unload_heads` exists?

**Comment by hai-nguyen-van** [comment]
I can confirm that `/sys/block/sda/device/unload_heads` does exist. When I hover the mouse cursor, I get the following error message:

![screenshot_hdapsicon](https://cloud.githubusercontent.com/assets/1613250/6214860/7230fb70-b604-11e4-891c-7cc0c74646ea.png)

**Comment by thpani** [comment]
Could you please post the output of

```
$ ls -al /sys/block/sda/device/unload_heads
$ cat /sys/block/sda/device/unload_heads
```

**Comment by hai-nguyen-van** [comment]
Here are the outputs:

```
$ ls -al /sys/block/sda/device/unload_heads
-rw-r--r-- 1 root root 4096 Feb 16 01:25 /sys/block/sda/device/unload_heads
$ cat /sys/block/sda/device/unload_heads
cat: /sys/block/sda/device/unload_heads: Operation not supported
$ sudo cat /sys/block/sda/device/unload_heads
cat: /sys/block/sda/device/unload_heads: Operation not supported
```

**Comment by thpani** [comment]
The errorcode `EOPNOTSUPP` indicates that the harddrive [does not support unloading](https://www.kernel.org/doc/Documentation/laptops/disk-shock-protection.txt).
If you are using the mainline `hdaps` driver, you may want to try `tp_smapi` instead.
